---
title: "Self-construal US data IRT analyses"
author: "Pooya Razavi"
date: "2023-04-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(mirt)
library(ggmirt)
df_us <- read.csv("C:/Users/pooya/Dropbox (Personal)/SelfConstrual IRT/US00_scored.csv")
df_sc_us <- df_us %>% 
              select(starts_with("selfconstrual"))

knitr::opts_chunk$set(echo = TRUE)
```


# The Structure

```{r}
#create a confirmatory structure
indep_model <- mirt.model('
   independent = 1-6')

inter_model <- mirt.model('
   interdependent = 7-12')
```


# Partial Credit Model

```{r}


#independent self-construal
  indep_results <- df_sc_us %>% select(selfconstrual_1:selfconstrual_6) %>% 
                  mirt(data = .,
                  model = indep_model,
                  itemtype = "Rasch",
                  SE = TRUE,
                  verbose = FALSE)
  summary(indep_results)
  independent_coef.pcm <- coef(indep_results, IRTpars=TRUE, simplify=TRUE)
  independent_coef.pcm$items
  
#interdependent self-construal
  inter_results <- df_sc_us %>% select(selfconstrual_7:selfconstrual_12) %>% 
                  mirt(data = .,
                  model = indep_model,
                  itemtype = "Rasch",
                  SE = TRUE,
                  verbose = FALSE)
  summary(inter_results)
  interdependent_coef.pcm <- coef(inter_results, IRTpars=TRUE, simplify=TRUE)
  interdependent_coef.pcm$items  

```

## Visualizations

```{r}
#Option Characteristic Curves
  #Independent
  plot(indep_results, type = 'trace', which.items = c(1, 2), 
       main = "Independent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  plot(indep_results, type = 'trace', which.items = c(3, 4), 
       main = "Independent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  plot(indep_results, type = 'trace', which.items = c(5, 6), 
       main = "Independent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  
  #Interdependent
  plot(inter_results, type = 'trace', which.items = c(1, 2), 
       main = "Interdependent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  plot(inter_results, type = 'trace', which.items = c(3, 4), 
       main = "Interdependent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  plot(inter_results, type = 'trace', which.items = c(5, 6), 
       main = "Interdependent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 

#Item Information Function
  #Independent
  plot(indep_results, type = 'infotrace', #which.items = c(1, 3), 
     main = "Independent Self-Construal", par.settings = simpleTheme(lwd=2))
  
  #Interdependent
  plot(inter_results, type = 'infotrace', #which.items = c(1, 3), 
     main = "Interdependent Self-Construal", par.settings = simpleTheme(lwd=2))

#total amount of information available from the items (i.e., TIF) 
  plot(indep_results, type = 'info', theta_lim = c(-4,4), lwd=2)  
  plot(inter_results, type = 'info', theta_lim = c(-4,4), lwd=2)  

#conditional standard error of measurement (i.e., cSEM)
  plot(indep_results, type = 'SE', theta_lim = c(-4,4), lwd=2) 
  plot(inter_results, type = 'SE', theta_lim = c(-4,4), lwd=2) 
```


# Generalized Partial Credit Model

```{r}

#independent self-construal
  indep_results <- df_sc_us %>% select(selfconstrual_1:selfconstrual_6) %>% 
                  mirt(data = .,
                  model = indep_model,
                  itemtype = "gpcm",
                  SE = TRUE,
                  verbose = FALSE)
  summary(indep_results)
  independent_coef.gpcm <- coef(indep_results, IRTpars=TRUE, simplify=TRUE)
  independent_coef.gpcm$items
  
#interdependent self-construal
  inter_results <- df_sc_us %>% select(selfconstrual_7:selfconstrual_12) %>% 
                  mirt(data = .,
                  model = indep_model,
                  itemtype = "gpcm",
                  SE = TRUE,
                  verbose = FALSE)
  summary(inter_results)
  interdependent_coef.pcm <- coef(inter_results, IRTpars=TRUE, simplify=TRUE)
  interdependent_coef.pcm$items  

```

## Visualizations

```{r}
#Option Characteristic Curves
  #Independent
  plot(indep_results, type = 'trace', which.items = c(1, 2), 
       main = "Independent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  plot(indep_results, type = 'trace', which.items = c(3, 4), 
       main = "Independent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  plot(indep_results, type = 'trace', which.items = c(5, 6), 
       main = "Independent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  
  #Interdependent
  plot(inter_results, type = 'trace', which.items = c(1, 2), 
       main = "Interdependent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  plot(inter_results, type = 'trace', which.items = c(3, 4), 
       main = "Interdependent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 
  plot(inter_results, type = 'trace', which.items = c(5, 6), 
       main = "Interdependent Self-Construal", par.settings = simpleTheme(lty=1:4,lwd=2),
       auto.key=list(points=FALSE,lines=TRUE, columns=4)) 

#Item Information Function
  #Independent
  plot(indep_results, type = 'infotrace', #which.items = c(1, 3), 
     main = "Independent Self-Construal", par.settings = simpleTheme(lwd=2))
  
  #Interdependent
  plot(inter_results, type = 'infotrace', #which.items = c(1, 3), 
     main = "Interdependent Self-Construal", par.settings = simpleTheme(lwd=2))

#total amount of information available from the items (i.e., TIF) 
  plot(indep_results, type = 'info', theta_lim = c(-4,4), lwd=2)  
  plot(inter_results, type = 'info', theta_lim = c(-4,4), lwd=2)  

#conditional standard error of measurement (i.e., cSEM)
  plot(indep_results, type = 'SE', theta_lim = c(-4,4), lwd=2) 
  plot(inter_results, type = 'SE', theta_lim = c(-4,4), lwd=2) 
```